./artisan make:model User
./artisan make:model User --all
./artisan make:model UserProfile --all
./artisan make:model Watches --all
./artisan make:model Categories --all
./artisan make:model Categories --help
./artisan make:model User --all
./artisan make:model UserProfile --all
./artisan make:model Watches --all
./artisan make:model Categories --all
./artisan make:model Images --all
./artisan make:model ShoppingCart --all
./artisan make:model CartItems --all
./artisan make:model Orders --all
./artisan make:model OrderItems --all
./artisan make:model Wishlist --all
./artisan make:model WishlistItems --all
./artisan make:model Reviews --all
./artisan make:model SupportTickets --all
./artisan make:model FAQ --all
./artisan make:model Feedback --all
